version: '3.8'

services:
  fantai:
    image: node:18-alpine
    container_name: fantai-app
    working_dir: /app
    command: >
      sh -c "
        echo '🚀 Avvio FantaAI...' &&
        apk add --no-cache postgresql-client curl &&
        echo '📦 Installazione dipendenze...' &&
        npm install &&
        echo '🔨 Build applicazione...' &&
        npm run build &&
        echo '🌐 Avvio server...' &&
        npm start
      "
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fantaseriea
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/fantaseriea
      SESSION_SECRET: your-super-secret-session-key-change-this-in-production
      NODE_ENV: production
      FOOTBALL_DATA_API_KEY: ${FOOTBALL_DATA_API_KEY}
      API_FOOTBALL_KEY: ${API_FOOTBALL_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "3000:5001"
    volumes:
      - /DATA/AppData/FantaAI:/app
      - /DATA/AppData/FantaAI/server/cache:/app/server/cache
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - fantai_network

  postgres:
    image: postgres:15-alpine
    container_name: fantai-postgres
    environment:
      POSTGRES_DB: fantaseriea
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - fantai_network

volumes:
  postgres_data:

networks:
  fantai_network:
    driver: bridge
