version: '3.8'

services:
  fantai:
    build: .
    container_name: fantai-app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fantaseriea
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/fantaseriea
      SESSION_SECRET: your-super-secret-session-key-change-this-in-production
      NODE_ENV: production
      FOOTBALL_DATA_API_KEY: ${FOOTBALL_DATA_API_KEY}
      API_FOOTBALL_KEY: ${API_FOOTBALL_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "3000:5001"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - fantai_network

  postgres:
    image: postgres:15-alpine
    container_name: fantai-postgres
    environment:
      POSTGRES_DB: fantaseriea
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - fantai_network

volumes:
  postgres_data:

networks:
  fantai_network:
    driver: bridge
