version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fantai-postgres
    environment:
      POSTGRES_DB: fantaseriea
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fantai_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  fantai:
    build: .
    container_name: fantai-app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fantaseriea
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/fantaseriea
      SESSION_SECRET: your-super-secret-session-key-change-this-in-production
      NODE_ENV: production
    ports:
      - "3000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fantai_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
    driver: local

networks:
  fantai_network:
    driver: bridge
